import {FETCH_DATA} from './type';

//initializing state
const initialState={
	data: [{
        "userId":1,
        "jobTitleName":"Developer",
        "firstName":"Romin",
        "lastName":"Irani",
        "employeeCode":"E1",
        "region":"CA",
        "phoneNumber":"408-1234567",
        "emailAddress":"Romin@gmail.com",
        "image":"https://thumbs.dreamstime.com/b/profile-picture-smiling-caucasian-male-employee-close-up-young-businessman-show-leadership-qualities-headshot-portrait-happy-204044575.jpg"
     },
     {
        "userId":2,
        "jobTitleName":"Developer",
        "firstName":"John",
        "lastName":"Antonio",
        "employeeCode":"E2",
        "phoneNumber":"408-31264567",
        "emailAddress":"John@gmail.com",
        "image":"https://thumbs.dreamstime.com/b/handsome-man-smiling-cheerful-big-smile-face-showing-teeth-positive-happy-expression-handsome-man-smiling-cheerful-212902822.jpg"
     },
     {
        "userId":3,
        "jobTitleName":"Tester",
        "firstName":"Brayden",
        "lastName":"Diego",
        "employeeCode":"E3",
        "phoneNumber":"408-91254567",
        "emailAddress":"Brayden@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/handsome-man-smiling-cheerful-big-260nw-1378645526.jpg"
     },
     {
        "userId":4,
        "jobTitleName":"Developer",
        "firstName":"Devin",
        "lastName":"Driss",
        "employeeCode":"E4",
        "phoneNumber":"408-10254567",
        "emailAddress":"Devin@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/portrait-young-businessman-blue-shirt-260nw-306245936.jpg"
     },
     {
        "userId":5,
        "jobTitleName":"Tester",
        "firstName":"Marco",
        "lastName":"Moshe",
        "employeeCode":"E5",
        "phoneNumber":"408-12054567",
        "emailAddress":"Marco@gmail.com",
        "image":"https://images.ctfassets.net/zykafdb0ssf5/3bKYtjKlAkv159agcEpRaU/4b76c7d08774e6d62ceb646b32acac79/johnnyheadshot.jpg"
     },
     {
        "userId":6,
        "jobTitleName":"Developer",
        "firstName":"Steffan",
        "lastName":"G",
        "employeeCode":"E6",
        "phoneNumber":"408-12254567",
        "emailAddress":"Steffan@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/profile-picture-confident-young-caucasian-260nw-1779265493.jpg"
     },
     {
        "userId":7,
        "jobTitleName":"Developer",
        "firstName":"Tao",
        "lastName":"K J",
        "employeeCode":"E7",
        "phoneNumber":"408-12854567",
        "emailAddress":"Tao@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/portrait-one-young-happy-cheerful-260nw-1949791540.jpg"
     },
     {
        "userId":8,
        "jobTitleName":"Tester",
        "firstName":"Devin",
        "lastName":"Driss",
        "employeeCode":"E8",
        "phoneNumber":"408-12754567",
        "emailAddress":"Romin@gmail.com",
        "image":"https://images.squarespace-cdn.com/content/v1/5b7e685d8ab722146afd7529/1564600902218-403CMIW9V4G2UC13A25W/PP_01.jpg"
     },
     {
        "userId":9,
        "jobTitleName":"Developer",
        "firstName":"Adelina",
        "lastName":"M B",
        "employeeCode":"E9",
        "phoneNumber":"408-12654567",
        "emailAddress":"Adelina@gmail.com",
        "image":"https://previews.123rf.com/images/dragonimages/dragonimages1611/dragonimages161100413/66967368-portrait-of-a-pretty-young-female-employee.jpg"
     },
     {
        "userId":10,
        "jobTitleName":"Lead",
        "firstName":"Ai",
        "lastName":"A",
        "employeeCode":"E10",
        "phoneNumber":"408-12554567",
        "emailAddress":"Ai@gmail.com",
        "image":"https://thumbs.dreamstime.com/b/young-female-employee-14787651.jpg"
     },
     {
        "userId":11,
        "jobTitleName":"Tester",
        "firstName":"Bhavika",
        "lastName":"V",
        "employeeCode":"E11",
        "phoneNumber":"408-12545167",
        "emailAddress":"Bhavika@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/happy-motivated-asian-female-employee-260nw-1498344446.jpg"
     },
     {
        "userId":12,
        "jobTitleName":"Developer",
        "firstName":"Cathenna",
        "lastName":"Amara",
        "employeeCode":"E12",
        "phoneNumber":"408-19254567",
        "emailAddress":"Cathenna@gmail.com",
        "image":"https://thumbs.dreamstime.com/b/office-lifestyle-business-people-concept-friendly-attractive-asian-female-employee-girl-showing-korean-heart-office-178655671.jpg"
     },
     {
        "userId":13,
        "jobTitleName":"Lead",
        "firstName":"Elanie",
        "lastName":"Faina",
        "employeeCode":"E13",
        "phoneNumber":"408-18254567",
        "emailAddress":"Elanie@gmail.com",
        "image":"https://thumbs.dreamstime.com/b/profile-picture-smiling-indian-female-employee-profile-picture-smiling-millennial-indian-female-employee-posing-office-198022033.jpg"
     },
     {
        "userId":14,
        "jobTitleName":"Developer",
        "firstName":"Malia",
        "lastName":"S",
        "employeeCode":"E14",
        "phoneNumber":"408-12354567",
        "emailAddress":"Malia@gmail.com",
        "image":"https://image.shutterstock.com/image-photo/asian-businesswoman-standing-while-using-260nw-1695867535.jpg"
     },
     {
        "userId":15,
        "jobTitleName":"Manager",
        "firstName":"Ethan",
        "lastName":"Hugo",
        "employeeCode":"E15",
        "phoneNumber":"408-51254567",
        "emailAddress":"Ethan@gmail.com",
        "image":"https://previews.123rf.com/images/jackf/jackf1706/jackf170600720/79632953-happy-female-employee-having-productive-day-at-work-in-office.jpg"
     }]
}

const sampleredux=(state=initialState,action)=>{
	switch(action.type){
		case FETCH_DATA:return{
			...state,
			data:state.data+action.payload
		}
		default:return state
	}
}

export default sampleredux;
